service: notes-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  profile: tibaNotes
  region: eu-north-1
  iam:
    role: arn:aws:iam::998245953721:role/tibaHotel-cloud

plugins:
  - serverless-webpack

package:
  individually: true

custom:
  webpack:
    concurrency: 3

functions:
  signUp:
    handler: functions/signUp/index.handler
    events:
      - httpApi:
          path: '/api/user/signup'
          method: POST
  login:
    handler: functions/login/index.handler
    events:
      - httpApi:
          path: '/api/user/login'
          method: POST
  saveNote:
    handler: functions/saveNote/index.handler
    events:
      - httpApi:
          path: '/api/notes'
          method: POST
  getNotes:
    handler: functions/getNotes/index.handler
    events:
      - httpApi:
          path: '/api/notes'
          method: GET
  updateNote:
    handler: functions/updateNote/index.handler
    events:
      - httpApi:
          path: '/api/notes'
          method: PUT
  removeNote:
    handler: functions/deleteNote/index.handler
    events:
      - httpApi:
          path: '/api/notes'
          method: DELETE
  restoreNote:
    handler: functions/restoreNote/index.handler
    events:
      - httpApi:
          path: '/api/restoreNote'
          method: POST

resources:
  Resources:
    notesDb:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: notes-db
        AttributeDefinitions:
          - AttributeName: id 
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    roomsDb:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: accounts
        AttributeDefinitions:
          - AttributeName: username 
            AttributeType: S
        KeySchema:
        - AttributeName: username
          KeyType: HASH
        BillingMode: PAY_PER_REQUEST
